### ISSUE TITLE
Issue installing/using the OVH module 

### ISSUE THREAD

**Issue by simon2k13** [cornelius-keller/ansible-ovh#1]
Hi Sir,

Thanks allot for sharing your plugin!!! I am trying to get it working but running into some issues. Here is what i have done so far: 
1. sudo pip install ovh
2. copy the ovh module inside /usr/share/ansible/ovh
3. added library path to /etc/ansible/ansible.cfg
4. Created Playbook with task like in documentation.
5. Getting an error

It seems that its trying to connect to a host to execute the play even if i put local_action in my playbook!
## Playbook

```
- local_action:
            ovh
            method=get
            endpoint=ovh-ca
            application_key=KEY
            application_secret=SECRET
            consumer_key=ID
            uri="/dedicated/server"
```
## Error:

```
Failed: [remote.host -> 127.0.0.1] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/home/simon/.ansible/tmp/ansible-tmp-1449379123.77-54031516730300/ovh", line 1699, in <module>
    main()
  File "/home/simon/.ansible/tmp/ansible-tmp-1449379123.77-54031516730300/ovh", line 1692, in main
    res =  method(module.params['uri']) # module.params['args'])
  File "/usr/local/lib/python2.7/dist-packages/ovh/client.py", line 290, in get
    return self.call('GET', _target, None, _need_auth)
  File "/usr/local/lib/python2.7/dist-packages/ovh/client.py", line 409, in call
    raise NotCredential(json_result.get('message'))
ovh.exceptions.NotCredential: This credential does not exist

FATAL: all hosts have already failed -- aborting
```

**Comment by cornelius-keller** [comment]
Hi simon2k13,

as the message "ovh.exceptions.NotCredential: This credential does not exist" tells you you are having a problem with the credentials at the ovh side. This is not an issue of the plugin. 
Try to recreate a new API key and make sure you can use all the methods like GET POST PUT DELETE.
 **Also make sure that it expires not to fast, I think the default lifetime of a key is just one day.**

Also be careful to post credentials here and be sure to revoke them if they are still valid because they may be used by other people to access your account.

Also note that the playbook is not trying to connect a host, it is trying to connect the ovh api which it should.

At least the error message shows that you reached the ovh api correctly using the plugin, just your credential seems to be invalid.

Hope that helps
Cornelius

**Comment by cornelius-keller** [comment]
Hi Simon,

any updates from you? Did you got it running?

**Comment by cornelius-keller** [comment]
I think this was a non existing token / authorization issue not related to the module. closing this now.
